### ISSUE TITLE
Support _extended field for utxo_info and script_utxos endpoints

### ISSUE THREAD

**Issue by fabianbormann** [edridudi/koios-java-client#167]
I don't know if the Koios API has changed, but unfortunately I was unable to get an inline datum from the [utxo_info call](https://preprod.koios.rest/#post-/utxo_info). 

It turned out, that the call does need to include the `_extended: true` get parameter to populate some fields such as `inline_datum`, which will be `null` otherwise. 

Is there currently a way to pass the get parameter to the [getTransactionInformation](https://github.com/cardano-community/koios-java-client/blob/main/src/main/java/rest/koios/client/backend/api/transactions/impl/TransactionsServiceImpl.java#L64C33-L64C58) method? 

Thx 🙏

**Comment by edridudi** [comment]
There were some breaking changes In Koios Instances.
I will publish a new version with alignment and post - Chang HF functionalities shortly.
