### ISSUE TITLE
Koios java client no longer compatible with Koios 1.0.7

### ISSUE THREAD

**Issue by DevStakePool** [edridudi/koios-java-client#71]
https://github.com/cardano-community/guild-operators/blob/koios-1.0.7/docs/Build/grest-changelog.md#107---for-all-networks

Several changes applied to HTTP end points that will need to be aligned.

I could try to take a look at it if needed

**Comment by DevStakePool** [comment]
Attached the test report showing the failing parts
[Test Results - All_in_koios-java-client.zip](https://github.com/cardano-community/koios-java-client/files/9690006/Test.Results.-.All_in_koios-java-client.zip)

**Comment by edridudi** [comment]
Yes, There were some breaking changes with Koios Instances,
Hence, Koios Java Client version 1.13 is incompatible with Koios Instances 1.0.7

[v1.14](https://github.com/cardano-community/koios-java-client/releases/tag/v1.14) has just been published.

Make sure to bump your Koios Java Client dependency to v1.14 in your project(s).

Successful Tests Using v1.14 can be seen here:
https://github.com/cardano-community/koios-java-client/actions/runs/3165077585

The compatibility chart in Readme has also been updated.

Thank you for reporting.
